### ISSUE TITLE
[bug] Table/DataTable preset "stacked-record-collection" removed between 18.12.11 and 18.12.14, breaking a shipped feature (SCR-215, #356/#641)

### ISSUE THREAD

**Issue by ecsol** [godx-jp/godxjp-ui#293]
## Summary

Table/DataTable preset "stacked-record-collection" removed between 18.12.11 and 18.12.14, breaking a shipped feature (SCR-215, #356/#641) in a real consumer app (dxs-platform/platform).

## Affected

- Component: `Table` / `DataTable` (both share the same `TablePresetProp` type)

## Reproduction (minimal)

1. In a project with @godxjp/ui@18.12.11 (or earlier, wherever "stacked-record-collection" was introduced), use:
```tsx
<Table preset="stacked-record-collection" collapseBelow="sm">
  <TableBody>
    <TableRow><TableCell label="Some Field">value</TableCell></TableRow>
  </TableBody>
</Table>
```
2. `npm/pnpm i @godxjp/ui@18.12.14` (or any 18.12.12+)
3. Run `tsc` — get:
   - `error TS2322: Type stacked-record-collection is not assignable to type 'TablePresetProp'`
   - `error TS2322: ... Property 'label' does not exist on type '... TableCellPriority ...'` for every `TableCell`
4. `grep -r "stacked-record-collection" node_modules/@godxjp/ui/dist/` returns **zero matches** — confirms it is genuinely gone, not renamed to something we missed.

## Expected

`TablePresetProp` should still include `"stacked-record-collection"` (or a documented, equivalent replacement): below `collapseBelow`, each table row collapses into a key-value stacked card at narrow viewports (390px), with each column's `label` rendered inline above its value — this satisfied SCR-215's requirement that all fields stay visible/stacked at mobile width without a horizontally-scrolling table. Consuming code also relied on a `label` prop on `TableCell` to supply the per-field label in the stacked-card view.

## Actual

In the published 18.12.14 package, `TablePresetProp` (`dist/props/vocabulary/data.prop.d.ts`) is now typed as exactly `"default" | "action-collection"` — `"stacked-record-collection"` is gone entirely, from both `Table` and `DataTable`. `TableCell` no longer accepts a `label` prop either (confirmed via a real `tsc` compile failure, not a guess).

This broke a real, already-shipped, redesign-accepted consumer page (`dxs-platform/platform`'s `resources/js/pages/Admin/ServiceAccounts.tsx`, SCR-215 / issue #356, accepted via issue #641) with **zero deprecation warning, no migration guide, and no CHANGELOG entry** (no CHANGELOG.md ships in the package at all). The only signal was `tsc` failing after bumping from 18.12.11 to 18.12.14.

We reverted our version pin to an exact `18.12.11` (not caret-ranged, since 18.12.12+ all appear to carry this regression) rather than ship the breakage or hand-roll a page-local replacement for an already-accepted design-system capability.

## Environment

- @godxjp/ui version: 18.12.14 (regression), last known-good: 18.12.11
- Consumer: dxs-platform/platform, pnpm workspace, React 19 + TypeScript, Node/pnpm 10.29.1

## Ask

- Either restore `"stacked-record-collection"` (and `TableCell.label`), or
- Ship a documented, equivalent replacement preset + a CHANGELOG/migration note, so consumers get a compile-time deprecation path instead of a silent capability removal.

**Comment by ecsol** [comment]
Restored and published as **@godxjp/ui@18.12.15** / **@godxjp/ui-mcp@18.12.15**.

- `TablePresetProp` regains `"stacked-record-collection"` (`src/props/vocabulary/data.prop.ts`).
- `Table` wraps with `.ui-table-stacked-collection`, `TableCell` gains a `label` prop rendered
  into the DOM (hidden above the collapse step, revealed below it) — `src/components/data-display/table.tsx`.
- New container-query CSS in `src/styles/table-layout.css`, mirroring `action-collection`'s
  architecture: measured against the table's own container, one block per canonical
  sm/md/lg/xl step, `<thead>` hidden below the step and each `<tr>` turned into a bordered
  key-value card.
- New themeable tokens in `src/tokens/components/table.css`
  (`--table-stacked-collection-card-padding-y/-x`, `-card-gap`, `-cell-padding-y`,
  `-label-font-size`).
- Full test file `src/components/data-display/__tests__/table-stacked-record-collection.test.tsx`
  (mirrors `table-action-collection.test.tsx`) — 9 tests, all passing. Full repo suite: 428 files /
  2689 tests, all green. MCP catalog/prop-sync/orphan/token-sync checks all pass.

Root cause confirmed: `git log --all -S "stacked-record-collection"` returned zero commits in this
repository's history before this fix — the preset was published to npm directly (≤18.12.11)
without ever landing a commit here, so a later direct-local-publish from a checkout that never had
it silently dropped the capability with no deprecation notice.

`dxs-platform/platform`'s `backend/package.json` is updated to `^18.12.15` (no version pin) and
its `pnpm types` / `pnpm build` both pass against the new release.

CHANGELOG: see `[18.12.15]` in CHANGELOG.md. Closing.
